version: "3.9"

services:
  web_menu-backend:
    container_name: web_menu-backend
    build:
      context: ../..
      dockerfile: build/Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    restart: on-failure
    volumes:
      - static_data:/static
      - media:/media
    env_file:
      - ../../environment/localhost/.env.local.docker
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - proj-postgres

  web_menu-postgres:
    image: postgres:14
    container_name: web_menu-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_menu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_data:
  media:
